//couple.js

var mongoose = require('mongoose');

var coupleSchema = mongoose.Schema({
		coupleid:Number,
		partner1FirstName: String,
		partner1MiddleName: String,
		partner1LastName: String,
		partner1HomePhone: String,
		partner1MobilePhone: String,
		partner1WorkPhone: String,
		partner1BirthDate: Date,
		partner1Age: Number,
		partner1BirthCity: String,
		partner1BirthState: String,
		partner1HomeStreetAddress: String,
		partner1HomeMailingAddress: String,
		partner1HomeCity: String,
		partner1HomeState: String,
		partner1HomeZipCode: String,
		partner1HomeEmail: String,
		partner1HomeTwitter: String,
		partner1WorkPlaceName: String,
		partner1WorkStreetAddress: String,
		partner1WorkMailingAddress: String,
		Partner1WorkCity: String,
		Partner1WorkState: String,
		partner1WorkZipCode: String,
		partner1WorkEmail: String,
		partner1WorkTwitter: String,
		partner1WorkJobPosition: String,
		partner1WorkJobDescription: String,
		partner1HasChildren: Boolean,
		partner1NumberOfChildren: Number,
		partner1MilitaryService: Boolean,
		partner1MilitaryDetails: String,
		partner1AllowCoriCheck: Boolean,
		partner1Activities: [],
		partner1Pets: Boolean,
		partner1PetType: String,
		partner1PetBreed: String,
		partner1PetName: String,
		partner1Married: Boolean,
		partner1CivilUnion: Boolean,

		// Partner 2 Details
		coupleid: Number,
		partner2FirstName: String,
		partner2MiddleName: String,
		partner2LastName: String,
		partner2HomePhone: String,
		partner2MobilePhone: String,
		partner2WorkPhone: String,
		partner2BirthDate: Date,
		partner2Age: Number,
		partner2BirthCity: String,
		partner2BirthState: String,
		partner2HomeStreetAddress: String,
		partner2HomeMailingAddress: String,
		partner2HomeCity: String,
		partner2HomeState: String,
		partner2HomeZipCode: String,
		partner2HomeEmail: String,
		partner2HomeTwitter: String,
		partner2WorkPlaceName: String,
		partner2WorkStreetAddress: String,
		partner2WorkMailingAddress: String,
		Partner2WorkCity: String,
		Partner2WorkState: String,
		partner2WorkZipCode: String,
		partner2WorkEmail: String,
		partner2WorkTwitter: String,
		partner2WorkJobPosition: String,
		partner2WorkJobDescription: String,
		partner2HasChildren: Boolean,
		partner2NumberOfChildren: Number,
		partner2MilitaryService: Boolean,
		partner2MilitaryDetails: String,
		partner2AllowCoriCheck: Boolean,
		partner2Activities: [],
		partner2Pets: Boolean,
		partner2PetType: String,
		partner2PetBreed: String,
		partner2PetName: String,
		partner1Married: Boolean,
		partner2CivilUnion: Boolean,

		// child 1
		
		childcoupleid:Number,
		childFirstName: String,
		childMiddleName: String,
		childLastName: String,
		childBirthDate: String,
		childAge: Number,
		childSexkey: boolean,
		childActivities: [],
		childLikes: [],
		childParent1: String,
		childParent2: String,
		childPets: Boolean,
		childPetType: String,
		childPetBreed: String,
		childPetName: String,

});

var Couple = mongoose.model('Couple', coupleSchema);

module.exports = Couple;